### ISSUE TITLE
Pyth EVM contract should accept prices outside of min/max timestamp if none were available within

### ISSUE THREAD

**Issue by beeb** [pyth-network/pyth-crosschain#1135]
In the following section, the Pyth contract checks for the validity of the provided price update:

https://github.com/pyth-network/pyth-crosschain/blob/16832aba5196dd1f46b7a3a152167c1cf3d664c0/target_chains/ethereum/contracts/contracts/pyth/Pyth.sol#L517-L530

As we see, it is a hard requirement that the publishTime of the update be within `[config.minTimestamp, config.maxTimestamp]`. However, it's possible that no signed VAA exists for the provided interval. In such a case, we would see the following for the price update:

`publishTime > config.maxTimestamp` AND `prevPublishTime < config.minTimestamp`

In such a case, the price update should be accepted as valid.

**Comment by jayantk** [comment]
Hi @beeb , thanks for reporting the issue.

If you are trying to get the first update after `minPublishTime`, regardless of how much later it is, I think you can solve this problem by setting maxTimestamp to infinity (?) Does that solution work for you?

**Comment by beeb** [comment]
Hey @jayantk thanks for the quick reply! I think you described what I'm looking for, that's perfect. Indeed, setting `checkUniqueness` to `true` and having `maxPublishTime` to the maximum value should achieve a validation of the next future price that is greater than or equal to `minPublishTime`.
