### ISSUE TITLE
Error: axios_1.default.create is not a function

### ISSUE THREAD

**Issue by AbhishekJadhav2002** [pyth-network/pyth-crosschain#1287]
I'm using `PriceServiceConnection` from `price-service-client`, currently it's throwing runtime error in my react app as,

Error:
```text
axios_1.default.create is not a function
TypeError: axios_1.default.create is not a function
    at new PriceServiceConnection
```

Code:
```javascript
const connection = new PriceServiceConnection("https://hermes.pyth.network");
```

package.json
```json
"dependencies": {
    "@pythnetwork/price-service-client": "^1.8.2",
    "@pythnetwork/pyth-sdk-solidity": "^2.4.0",
    "@web3modal/ethereum": "^2.3.0",
    "@web3modal/react": "^2.3.0",
    "axios": "^1.6.7",
    "ethers": "^5.7.2",
    "lodash.debounce": "^4.0.8",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-qr-code": "^2.0.12",
    "react-query": "^3.39.3",
    "react-router-dom": "^6.21.3",
    "react-scripts": "5.0.1",
    "react-toastify": "^10.0.3",
    "sass": "^1.70.0",
    "wagmi": "^0.12.12"
  },
  "devDependencies": {
    "@typechain/ethers-v5": "^11.1.2",
    "@types/lodash.debounce": "^4.0.9",
    "@types/node": "^16.18.71",
    "@types/react": "^18.2.48",
    "@types/react-dom": "^18.2.18",
    "@typescript-eslint/eslint-plugin": "^6.19.0",
    "@typescript-eslint/parser": "^6.19.0",
    "eslint": "^8.56.0",
    "eslint-plugin-react": "^7.33.2",
    "typechain": "^8.3.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },
```

Note: I have installed axios for other APIs, I tried installing specific version reauired by price-service-client but that didn't help.

**Comment by guibescos** [comment]
Hi thanks so much for reaching out!

Can you provide a minimal example in the form of a github repo so we can look?

**Comment by AbhishekJadhav2002** [comment]
Thank you @guibescos for the reply, you can find the demo implementation [here](https://github.com/AbhishekJadhav2002/synthetix-demo/blob/b859c43a8a14916b47201f4882d61b3eacac426b/src/components/Futures/Inputs.tsx#L61)

**Comment by guibescos** [comment]
@AbhishekJadhav2002 I'm observing the same issue, have you found solution. Can you try using @pythnetwork/price-service-client v1.8.0

**Comment by guibescos** [comment]
This is a bug in create-react-app and cjs packages as seen in this issue https://github.com/facebook/create-react-app/issues/11889 . A solution is using craco with craco.config.js:

```
module.exports = {
    webpack: {
        configure: (config) => {
            // ...
            const fileLoaderRule = getFileLoaderRule(config.module.rules);
            if(!fileLoaderRule) {
                throw new Error("File loader not found");
            }
            fileLoaderRule.exclude.push(/\.cjs$/);
            // ...
	    return config;
        }
    }
};

function getFileLoaderRule(rules) {
    for(const rule of rules) {
        if("oneOf" in rule) {
            const found = getFileLoaderRule(rule.oneOf);
            if(found) {
                return found;
            }
        } else if(rule.test === undefined && rule.type === 'asset/resource') {
            return rule;
        }
    }
}

```

**Comment by guibescos** [comment]
Closing, feel free to reopen if still struggling

**Comment by guibescos** [comment]
Closing, feel free to reopen if you still encounter or the fixes don't work.

**Comment by AbhishekJadhav2002** [comment]
> This is a bug in create-react-app and cjs packages as seen in this issue [facebook/create-react-app#11889](https://github.com/facebook/create-react-app/issues/11889) . A solution is using craco with `craco.config.js`:
> 
> ```
> module.exports = {
>     webpack: {
>         configure: (config) => {
>             // ...
>             const fileLoaderRule = getFileLoaderRule(config.module.rules);
>             if(!fileLoaderRule) {
>                 throw new Error("File loader not found");
>             }
>             fileLoaderRule.exclude.push(/\.cjs$/);
>             // ...
> 	    return config;
>         }
>     }
> };
> 
> function getFileLoaderRule(rules) {
>     for(const rule of rules) {
>         if("oneOf" in rule) {
>             const found = getFileLoaderRule(rule.oneOf);
>             if(found) {
>                 return found;
>             }
>         } else if(rule.test === undefined && rule.type === 'asset/resource') {
>             return rule;
>         }
>     }
> }
> ```

I added craco in the project and it solved the issue. Thank you @guibescos !
