### ISSUE TITLE
Cargo complaning about unmatchable version requirements with `pyth-solana-receiver-sdk` and `serde_with` crates

### ISSUE THREAD

**Issue by lopeselio** [pyth-network/pyth-crosschain#1752]
Stack Exchange: [Cargo complaning about unmatchable version requirements with `pyth-solana-receiver-sdk` and `serde_with` crates](https://solana.stackexchange.com/questions/15109/cargo-complaning-about-unmatchable-version-requirements-with-pyth-solana-receiv)

I'm trying to add creating a stub Pyth Solana Receiver. Encountered some dependency issues even though I have used the right version of `serde_with` that is compatible with 1solana-sdk` used in the repo `v1.16.0`. Do you have any recommendations? 
(as seen here)[https://github.com/solana-labs/solana/blob/v1.16.20/Cargo.toml#L284)

**Comment by mubarizkyc** [comment]
Is it same as #1759

**Comment by guibescos** [comment]
gm @lopeselio ,

I cloned your branch from https://github.com/lopeselio/pyth-crosschain/tree/pyth-solana-stub.
I am not encountering the error with :
`solana-cli 1.18.17`
`anchor-cli 0.30.1`

**Comment by lopeselio** [comment]
Hi @guibescos let me check it out. Thanks for the input

**Comment by lopeselio** [comment]
Thanks @guibescos . I will continue to complete the rest of the task of creating the testing stub for the Pyth Pull Oracle
