### ISSUE TITLE
Price publisher address on zkSync goerli testnet seems to be outdated

### ISSUE THREAD

**Issue by sunpuyo** [pyth-network/pyth-crosschain#655]
Currently, `0xF532F2C1bB7b67E08f7D8B76f9fF804D0831725e` address is indicated in the official document, but the contract does not actually exist. 
Perhaps the zkSync testnet was reset in Feb after the contract was deployed in Jan.
Can you redeploy the contract and update the address?

**Comment by ali-bahjati** [comment]
Thanks for letting us know, we fixed it in #697
