### ISSUE TITLE
basename : The term 'basename' is not recognized as the name of a cmdlet,

### ISSUE THREAD

**Issue by TBomberman** [pyth-network/pyth-crosschain#788]
This comes from running build-contracts.ts script on windows platform.

It looks like basename is a command in unix/linux and not windows. It would be nice to specify that in the readmes.

**Comment by jayantk** [comment]
hey @TBomberman are you referring to the cosmwasm contract build? If so, do you mind sending a PR that uses the javascript file api to get those paths instead of using the unix commands?

**Comment by TBomberman** [comment]
Fine I guess it's just assumed from the Injective docs.
