### ISSUE TITLE
Make @pythnetwork/wormhole-attester-sdk NPM public

### ISSUE THREAD

**Issue by dileepfrog** [pyth-network/pyth-crosschain#796]
This package is referenced by the price service JS REST server, but is not visible on NPM: https://github.com/pyth-network/pyth-crosschain/blob/e7b72bf5c3761f8b4b9ad20f0a3d6d679dea6026/price_service/server/package.json#L36

I'm guessing this is currently published as a private NPM, please make available as public if so. Thank you!

**Comment by guibescos** [comment]
This is a local dependency, and get included in `@pythnetwork/price-service-server` automatically when `@pythnetwork/price-service-server` gets built.
Why do you want it to be public?

**Comment by dileepfrog** [comment]
For my application, I would like to grab the latest price feed data from the `price_service` REST API in both human-readable JSON form along with its corresponding encoded form suitable for calling `updatePriceFeeds` on-chain. From what I understand, this requires two separate calls to the REST API, and there is no way to guarantee the data returned from both responses represent exactly the same set of VAAs.

As a solution, I had the idea of only obtaining the encoded update data from the REST API in a single call, and decoding it on the client end directly using `parsePriceAttestation` from `@pythnetwork/wormhole-attester-sdk` into human-readable form.

Please let me know if there's a better way to achieve this or if I'm missing something, thanks.

**Comment by dileepfrog** [comment]
Beautiful, this is exactly what I was after, thanks for pointing me in the right direction!
