### ISSUE TITLE
Document why IPyth.parsePriceFeedUpdates requires a fee

### ISSUE THREAD

**Issue by dileepfrog** [pyth-network/pyth-crosschain#797]
Documentation notes that `updatePriceFeeds` requires a small fee for storing new prices on-chain, however it's unclear why `parsePriceFeedUpdates` also requires a fee when it does not actually commit to on-chain storage. 

https://github.com/pyth-network/pyth-crosschain/blob/e7b72bf5c3761f8b4b9ad20f0a3d6d679dea6026/target_chains/ethereum/sdk/solidity/IPyth.sol#L122

**Comment by jayantk** [comment]
@dileepfrog it requires a fee because pyth needs to reward its data providers for providing data. It's the same reason as the method that stores the data (the Pyth contract doesn't need to pay a fee for the on-chain storage; that's included in the tx gas cost)
