### ISSUE TITLE
contract dependency about wormhole

### ISSUE THREAD

**Issue by WayneAl** [pyth-network/pyth-crosschain#798]
https://github.com/pyth-network/pyth-crosschain/blob/1dab5b37d64adeb8545ff958f8d60fe513448b8f/target_chains/sui/contracts/Move.toml#L11

Please change to using `git dependency`, then we can directly use in our package

USAGE: 

`Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/sui/contracts/", rev = "sui/audit_fixes"}`

ERROR:

```
Caused by:
    0: Resolving dependencies for package 'Pyth'
    1: Path cannot access parent of current directory: ../wormhole/sui/wormhole.
```

**Comment by jayantk** [comment]
thank you @WayneAl for reporting. @optke3 has been working on all of the sui stuff and will take a look at this.
