### ISSUE TITLE
Ethereum OracleSwap exmaple package issue

### ISSUE THREAD

**Issue by vincracker** [pyth-network/pyth-crosschain#834]
When I tried to run the app frontend, it said cannot find module '@pythnetwork/pyth-evm-js' or its corresponding type declarations. as the pyth-evm-js has been moved to pyth-crosschain, which package should I change to?

<img width="1390" alt="Screenshot 2023-05-23 at 4 47 46 PM" src="https://github.com/pyth-network/pyth-crosschain/assets/100567860/d8f5f3fc-04a4-4b1a-aac5-e47ee5a267df">

**Comment by jayantk** [comment]
hi @vincracker thank you for reporting. I think the code for both of those packages should be in the pyth-crosschain repo as well. Can you try running:

`npx lerna run build` 

from the root of the pyth-crosschain repo, then try ^ again and see if that fixes the problem? 

Another option is to replace the package version for the missing packages with the latest version from npm which you can find here: https://www.npmjs.com/package/@pythnetwork/pyth-evm-js

**Comment by vincracker** [comment]
Hi @jayantk  Thank you for you reply, I have tried your command, it fixed the issue. But a new issue showed up after I tried to run `npm run dev` on the app folder.
<img width="1618" alt="Screenshot 2023-05-24 at 12 21 40 PM" src="https://github.com/pyth-network/pyth-crosschain/assets/100567860/6beae5f1-b89d-4b91-b884-36a9fd729f81">

**Comment by vincracker** [comment]
Hi @jayantk Thank you for your reply, now the frontend works, but I got following warning when I run `npm run start` after run your command `npx lerna run build`.
<img width="901" alt="Screenshot 2023-05-24 at 3 15 23 PM" src="https://github.com/pyth-network/pyth-crosschain/assets/100567860/49516692-8d9f-416b-bdfb-79da4e146d48">

And when I clicked submit on the frontend it showed runtime error.
<img width="1069" alt="Screenshot 2023-05-24 at 3 15 50 PM" src="https://github.com/pyth-network/pyth-crosschain/assets/100567860/a0596710-f532-4010-a8e5-d3bfe2ae433b">

**Comment by jayantk** [comment]
@vincracker Is your wallet set to the polygon mumbai network? The frontend points to a specific contract address, which only exists on certain networks. The default contract address is for the polygon mumbai network. Try setting your wallet to th at network and trying again?

**Comment by vincracker** [comment]
Yes, seems the issue is here. The argument should be priceFeedUpdateData not priceFeedUpdateData.length
<img width="349" alt="Screenshot 2023-05-25 at 4 34 20 PM" src="https://github.com/pyth-network/pyth-crosschain/assets/100567860/9eef7d18-008f-4146-9dcf-9fe1084dcdcc">

**Comment by jayantk** [comment]
fixed by https://github.com/pyth-network/pyth-crosschain/pull/856
